#!/usr/bin/env python3
"""PC stand-in for firmware `esp_gsp_timer_create(ui, 250, feed_load)`.

Official `sim` does not run C timers. Drive the `load` bind through the
application backend JSON-RPC channel (`set_value`), matching GSP_BIND_LOAD.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parents[2] / "tools" / "gsp-sim"
sys.path.insert(0, str(TOOLS_DIR))
from sim_rpc import SimBackend  # noqa: E402

# Generated by gspc as GSP_BIND_LOAD in hello_binds.h.
LOAD_BIND_ID = 1
PERIOD_S = 0.25
STEP = 5


def feed_load(backend: SimBackend, load: int) -> int:
    load = (load + STEP) % 101
    backend.call("set_value", {"bind_id": LOAD_BIND_ID, "value": load})
    return load


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8684)
    args = parser.parse_args()

    backend = SimBackend(host=args.host, port=args.port)
    try:
        backend.call("capabilities")
        load = 0
        due = time.monotonic() + PERIOD_S
        while True:
            backend.poll(max(0.0, due - time.monotonic()))
            now = time.monotonic()
            if now >= due:
                load = feed_load(backend, load)
                due = now + PERIOD_S
    except RuntimeError as error:
        print(error, file=sys.stderr)
        return 1
    except (ConnectionError, KeyboardInterrupt):
        return 0
    finally:
        backend.close()


if __name__ == "__main__":
    raise SystemExit(main())
